/**
 * The PDF writer.
 *
 * The structural assertions here are the ones a reader actually validates: the
 * header, the object count, and an xref table whose offsets land exactly on
 * their objects. The output has also been read back by an independent parser
 * (pypdf) — three pages, repeating headers, page numbers, and every figure
 * intact — and this file is what keeps it that way.
 */
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import {
  buildPdf, encodeWinAnsi, fitColumns, pageSize, textWidth, truncateToWidth,
  usableWidth, type PdfDoc,
} from './pdf';

const doc = (over: Partial<PdfDoc> = {}): PdfDoc => ({
  title: 'Stokman Rozen Kenya Ltd — August 2026',
  subtitle: 'Monthly statement',
  meta: [{ label: 'Statement no', value: 'VC-SCH-SRK-202608-01' }],
  columns: [
    { header: 'DATE', width: 52 },
    { header: 'NAME', width: 110, flex: true },
    { header: 'TOTAL', width: 50, align: 'right' },
  ],
  rows: [
    ['2026-08-01', 'TABITHA KAGOI', '1,150.00'],
    ['2026-08-02', 'CALVIN KLEIN', '550.00'],
  ],
  totals: ['', '2 visits', '1,700.00'],
  footer: 'Generated by Vitcare Clinic',
  ...over,
});

describe('encodeWinAnsi', () => {
  test('passes ASCII through unchanged', () => {
    assert.equal(encodeWinAnsi('KSh 1,234.56').toString('latin1'), 'KSh 1,234.56');
  });

  test('maps the punctuation the UI copy actually uses', () => {
    // en dash, em dash, curly quotes, bullet, ellipsis
    assert.deepEqual([...encodeWinAnsi('–—‘’“”•…')], [0x96, 0x97, 0x91, 0x92, 0x93, 0x94, 0x95, 0x85]);
  });

  test('keeps the middle dot, which is the same byte in Latin-1 and WinAnsi', () => {
    assert.deepEqual([...encodeWinAnsi('·')], [0xb7]);
  });

  test('keeps accented Latin-1 letters', () => {
    assert.deepEqual([...encodeWinAnsi('é')], [0xe9]);
  });

  test('substitutes ? for what it cannot represent, rather than dropping it', () => {
    // A dropped character makes "Wanjirũ" render as "Wanjir", which reads like
    // a correct name. The ? is visible, and visible is the point.
    assert.equal(encodeWinAnsi('Wanjirũ').toString('latin1'), 'Wanjir?');
  });

  test('turns newlines into spaces so a pasted note cannot break the layout', () => {
    assert.equal(encodeWinAnsi('a\nb\rc').toString('latin1'), 'a b c');
  });
});

describe('textWidth / truncateToWidth', () => {
  test('measures a digit at 556/1000 em', () => {
    assert.equal(Math.round(textWidth('0', 10) * 100) / 100, 5.56);
  });

  test('leaves a string that already fits alone', () => {
    assert.equal(truncateToWidth('short', 8.5, 500), 'short');
  });

  test('cuts with an ellipsis and stays inside the budget', () => {
    const long = 'cipro/flagyl/zinc/ors/pcm/trugel/iv omez/tramadol';
    const out = truncateToWidth(long, 8.5, 60);
    assert.equal(out.endsWith('...'), true);
    assert.equal(textWidth(out, 8.5) <= 60, true);
  });

  test('returns empty rather than an ellipsis alone when there is no room', () => {
    assert.equal(truncateToWidth('anything', 8.5, 2), '');
  });
});

describe('fitColumns', () => {
  test('gives a fixed column enough room for its widest value', () => {
    // The regression this exists for: a 50pt TOTAL column once ellipsized
    // "150,000.00" to "150,000..." on a customer's statement.
    const d = doc({
      columns: [
        { header: 'NAME', width: 200, flex: true },
        { header: 'TOTAL', width: 20, align: 'right' },
      ],
      rows: [['X', '150,000.00']],
      totals: ['', '1,980,000.00'],
    });
    const [, total] = fitColumns(d, 515);
    assert.equal(total >= textWidth('1,980,000.00', 8.5) + 8, true);
  });

  test('never truncates a fixed column, whatever the page width', () => {
    const d = doc({
      columns: [{ header: 'TOTAL', width: 10, align: 'right' }],
      rows: [['1,234,567.89']],
      totals: undefined,
    });
    const [w] = fitColumns(d, 515);
    assert.equal(truncateToWidth('1,234,567.89', 8.5, w - 8), '1,234,567.89');
  });

  test('shares the leftover between the flexible columns, by their asked ratio', () => {
    const d = doc({
      columns: [
        { header: 'A', width: 100, flex: true },
        { header: 'B', width: 300, flex: true },
      ],
      // Long enough that neither column's content caps its share.
      rows: [['x'.repeat(300), 'y'.repeat(300)]],
      totals: undefined,
    });
    const [a, b] = fitColumns(d, 400);
    assert.equal(Math.round(b / a), 3);
  });

  test('does not grow a flexible column past what its content needs', () => {
    const d = doc({
      columns: [
        { header: 'A', width: 100, flex: true },
        { header: 'B', width: 100, flex: true },
      ],
      rows: [['hi', 'there']],
      totals: undefined,
    });
    const [a] = fitColumns(d, 515);
    assert.equal(a < 100, true);
  });

  test('falls back to the asked width when the fixed columns leave no room', () => {
    const d = doc({
      columns: [
        { header: 'A', width: 80, flex: true },
        { header: 'TOTAL', width: 10, align: 'right' },
      ],
      rows: [['x', 'y'.repeat(200)]],
      totals: undefined,
    });
    const [a] = fitColumns(d, 100);
    assert.equal(a, 80);
  });
});

describe('pageSize', () => {
  test('is A4 portrait by default', () => {
    assert.deepEqual(pageSize({}), { width: 595.28, height: 841.89 });
  });

  test('turns the page on its side when asked', () => {
    // The scheme register has twelve columns; portrait would force a dropped
    // column or unreadably short drug lists.
    assert.deepEqual(pageSize({ landscape: true }), { width: 841.89, height: 595.28 });
  });

  test('gives a landscape table noticeably more room', () => {
    assert.equal(usableWidth({ landscape: true }) > usableWidth({}) + 200, true);
  });
});

describe('buildPdf', () => {
  const text = () => buildPdf(doc()).toString('latin1');

  test('declares itself a PDF and ends where a reader looks for the end', () => {
    const s = text();
    assert.equal(s.startsWith('%PDF-1.4'), true);
    assert.equal(s.trimEnd().endsWith('%%EOF'), true);
  });

  test('marks itself binary, so no transfer converts its line endings', () => {
    const buf = buildPdf(doc());
    assert.deepEqual([...buf.subarray(9, 15)], [0x25, 0xe2, 0xe3, 0xcf, 0xd3, 0x0a]);
  });

  test('writes an xref whose every offset lands on its own object', () => {
    // The one structural thing a reader really checks. An offset that is out by
    // a byte produces a file that opens in one viewer and not another.
    const buf = buildPdf(doc());
    const s = buf.toString('latin1');
    const startxref = Number(/startxref\s+(\d+)/.exec(s)?.[1]);
    assert.equal(s.slice(startxref, startxref + 4), 'xref');
    const size = Number(/\/Size (\d+)/.exec(s)?.[1]);
    const entries = [...s.slice(startxref).matchAll(/^(\d{10}) 00000 n $/gm)].map((m) => Number(m[1]));
    assert.equal(entries.length, size - 1);
    entries.forEach((offset, i) => {
      assert.equal(s.slice(offset, offset + `${i + 1} 0 obj`.length), `${i + 1} 0 obj`);
    });
  });

  test('states a stream length that matches the bytes it wrote', () => {
    const s = text();
    for (const m of s.matchAll(/<< \/Length (\d+) >>\nstream\n/g)) {
      const declared = Number(m[1]);
      const start = m.index + m[0].length;
      assert.equal(s.slice(start + declared, start + declared + 10), '\nendstream');
    }
  });

  test('references both base-14 fonts and embeds neither', () => {
    const s = text();
    assert.match(s, /\/BaseFont \/Helvetica \/Encoding \/WinAnsiEncoding/);
    assert.match(s, /\/BaseFont \/Helvetica-Bold \/Encoding \/WinAnsiEncoding/);
    assert.equal(s.includes('/FontFile'), false);
  });

  test('escapes parentheses and backslashes in a name', () => {
    // An unescaped ')' closes the string early and corrupts the page, and names
    // with parentheses do reach clinical systems.
    const s = buildPdf(doc({ rows: [['x', 'SMITH (JNR) \\ CO', '1.00']] })).toString('latin1');
    assert.match(s, /SMITH \\\(JNR\\\) \\\\ CO/);
  });

  test('paginates and numbers every page', () => {
    const rows = Array.from({ length: 200 }, (_, i) => [`2026-08-01`, `PATIENT ${i}`, '100.00']);
    const s = buildPdf(doc({ rows })).toString('latin1');
    const count = Number(/\/Type \/Pages \/Count (\d+)/.exec(s)?.[1]);
    assert.equal(count > 1, true);
    for (let i = 1; i <= count; i += 1) {
      assert.equal(s.includes(`(Page ${i} of ${count})`), true);
    }
  });

  test('repeats the title and column headers on every page', () => {
    const rows = Array.from({ length: 200 }, () => ['2026-08-01', 'X', '1.00']);
    const s = buildPdf(doc({ rows })).toString('latin1');
    const count = Number(/\/Type \/Pages \/Count (\d+)/.exec(s)?.[1]);
    assert.equal([...s.matchAll(/\(DATE\) Tj/g)].length, count);
  });

  test('renders totals in the bold font', () => {
    const s = text();
    assert.match(s, /\/F2 8\.5 Tf[^E]*\(1,700\.00\) Tj/);
  });

  test('writes the landscape media box into every page object', () => {
    const s = buildPdf(doc({ landscape: true })).toString('latin1');
    assert.match(s, /\/MediaBox \[0 0 841\.89 595\.28\]/);
    assert.equal(s.includes('/MediaBox [0 0 595.28 841.89]'), false);
  });

  test('handles a document with no rows at all', () => {
    const s = buildPdf(doc({ rows: [], totals: undefined })).toString('latin1');
    assert.match(s, /\/Type \/Pages \/Count 1/);
    assert.equal(s.trimEnd().endsWith('%%EOF'), true);
  });
});
